[package]
name = "componentize-py"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.4", features = [ "derive" ] }
tar = "0.4.38"
tempfile = "3.3.0"
wizer = "1.6.0"
zstd = "0.10.0"

[build-dependencies]
anyhow = "1.0.68"
tar = "0.4.38"
zstd = "0.10.0"

[workspace]
members = [
  "runtime",
  "shared"
]
